# Generated by Django 4.2.7 on 2023-12-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paurakh', '0002_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='profileImage',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='about',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='fullName',
            field=models.CharField(max_length=20),
        ),
    ]
