# Generated by Django 4.2.7 on 2023-12-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paurakh', '0003_rename_profileimage_about_photo_alter_about_position_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagoryies',
            new_name='Catagory',
        ),
    ]
