# Generated by Django 4.2.7 on 2023-12-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paurakh', '0007_rename_categoryiesname_category_categoriesname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoriesName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='Categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skillName',
            new_name='skill_name',
        ),
    ]
