# Generated by Django 4.2.7 on 2023-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paurakh', '0008_rename_categoriesname_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
