# Generated by Django 4.2.7 on 2023-12-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paurakh', '0009_alter_logo_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
